import { Poppins, Inter, Fredoka, Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import ClientWrapper from "@/components/ClientWrapper";
import LoaderWrapper from "@/components/LoaderWrapper"; 

const poppins = Poppins({ subsets: ["latin"], weight: ["400"], variable: "--font-poppins" });
const inter = Inter({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-inter" });
const fredoka = Fredoka({ subsets: ["latin"], weight: ["700"], variable: "--font-fredoka" });
const roboto = Roboto({ subsets: ["latin"], weight: ["700"], variable: "--font-roboto" });

export const metadata = {
  title: "Mauna",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} ${fredoka.variable} ${roboto.variable} antialiased`}
      >
        <LoaderWrapper>
          <ClientWrapper>{children}</ClientWrapper>
          <Toaster position="top-right" reverseOrder={false} />
        </LoaderWrapper>
      </body>
    </html>
  );
}
